## Lab 8 ##

Kar Lok Ng
8971216

### Pytorch Section ###

In [16]:
import torch 
import numpy as np

In [28]:
# Dot product of two vectors each of length 3
torch.manual_seed(42)
vect1 = torch.rand(3)
vect2 = torch.rand(3)

print("Original vectors: ")
print(vect1)
print(vect2)
print("Dot product of these two vectors: ")
print(torch.dot(vect1, vect2))
print("")

# Matrix multiplication of two 2D matrices, each (2,2).
mat1 = torch.rand(2,2)
mat2 = torch.rand(2,2)

print("Original matrices: ")
print(mat1)
print(mat2)
print("Matrix multiplication of these matrices: ")
print(torch.matmul(mat1, mat2))

Original vectors: 
tensor([0.8823, 0.9150, 0.3829])
tensor([0.9593, 0.3904, 0.6009])
Dot product of these two vectors: 
tensor(1.4337)

Original matrices: 
tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])
tensor([[0.9346, 0.5936],
        [0.8694, 0.5677]])
Matrix multiplication of these matrices: 
tensor([[0.9298, 0.6029],
        [0.9950, 0.6340]])


### Tensorflow Section ###

In [1]:
import tensorflow as tf

In [16]:
# Dot product of two vectors each of length 3
vect1 = tf.constant([0.8823, 0.9150, 0.3829])
vect2 = tf.constant([0.9593, 0.3904, 0.6009])

print("Dot product of these two vectors: ")
print(tf.tensordot(vect1, vect2, axes= 1))

# Matrix multiplication of two 2D matrices.
mat1 = tf.constant([[0.2566, 0.7936], [0.9408, 0.1332]])
mat2 = tf.constant([[0.9346, 0.5936], [0.8694, 0.5677]])

print("")
print("Matrix mulitplication of these two matrices: ")

# Seems like there's 2 ways to do matrix multiplication in tf
# Although the tensordot way seems a little strange to me
# with the axes argument being a bit difficult to parse right now
# Will look into it for the future.
print(tf.tensordot(mat1, mat2, axes= [[1], [0]]))
print(tf.linalg.matmul(mat1, mat2))

Dot product of these two vectors: 
tf.Tensor(1.433691, shape=(), dtype=float32)

Matrix mulitplication of these two matrices: 
tf.Tensor(
[[0.9297742  0.6028445 ]
 [0.99507576 0.63407654]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.9297742  0.6028445 ]
 [0.99507576 0.63407654]], shape=(2, 2), dtype=float32)
